working

diff --git a/.github/workflows/create_release_branch.yml b/.github/workflows/create_release_branch.yml
--- a/.github/workflows/create_release_branch.yml
+++ b/.github/workflows/create_release_branch.yml
@@ -6,7 +6,8 @@ on:
       target:
         description: 'Target version to compare. If omitted, the latest release from github will be used. Exmaple: v1.2.3'
         required: false
-
+env:
+  VERSION_REGEX: ^v\d+\.\d+\.\d+$
 jobs:
   get-prs:
     name: Parse PRs labels and create next release branch
@@ -16,79 +17,58 @@ jobs:
       pull-requests: write
       repository-projects: write
     outputs:
-      new_branch: ${{ steps.new-branch.outputs.new_branch }}
+      new_branch: ${{ steps.get-next-version.outputs[steps.get_increment_type.outputs.increment_type] }}
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
       
-      - name: "Get default branch sha"
+      - name: Get default branch sha
         id: get_sha
         run: |
-           BASE_SHA=$(git rev-parse ${{ github.event.repository.default_branch }})
-           echo "BASE_SHA=$BASE_SHA" >> $GITHUB_ENV
-           echo "Release branch will be cut from $BASE_SHA"
+          BASE_SHA=$(git rev-parse master)
+          echo "BASE_SHA=$BASE_SHA" >> $GITHUB_ENV
+          echo "Release branch will be cut from master at $BASE_SHA"
       
-      - name: "Get latest release"
+      - name: Get latest released tag
+        id: latest_tag
         if: ${{ inputs.target == '' }}
-        id: get_latest_release
-        uses: InsonusK/get-latest-release@v1.1.0
+        uses: oprypin/find-latest-tag@v1
         with:
-          myToken: ${{ github.token }}
-          exclude_types: "draft|prerelease"
+          repository: man-group/ArcticDB
+          regex: ${{ env.VERSION_REGEX }}
+          sort-tags: true
+          releases-only: true
 
-      - name: Verify branch format
-        id: verify_branch
-        uses: actions/github-script@v7
-        with:
-          script: |
-            const target = '${{ inputs.target || steps.get_latest_release.outputs.tag_name }}';
-            const targetPattern = /^v(\d+)\.(\d+)\.(\d+)$/;
-            if (targetPattern.test(target)) {
-              const targetBranch = target.slice(1);
-              core.setOutput('target_branch', targetBranch);
-            } else {
-              core.setFailed('Error: Target tag is not in the valid vX.Y.Z format');
-            }
-
-      - name: Get prs between
-        uses: VanOns/get-merged-pull-requests-action@v1
+      - name: Get prs between master (${{ env.BASE_SHA }}) and ${{ inputs.target || steps.latest_tag.outputs.tag }}
+        uses: VanOns/get-merged-pull-requests-action@master
         id: pull_requests
         with:
-          repo: ognyanstoimenov/ArcticDB
           github_token: ${{ github.token }}
           current_tag: ${{ env.BASE_SHA }}
-          previous_tag: ${{ steps.verify_branch.outputs.target_branch }}
+          previous_tag: ${{ inputs.target || steps.latest_tag.outputs.tag }}
           return_type: "all"
 
       - name: Get labels of PRs and determine increment type
         id: get_increment_type
-        uses: actions/github-script@v7
         env:
           PULL_REQUESTS: ${{ steps.pull_requests.outputs.pull_requests }}
           MAJOR_LABEL: major
           MINOR_LABEL: minor
           PATCH_LABEL: patch
-        with:
-          script: |
-            if (!process.env.PULL_REQUESTS) {
-              core.setFailed('Error: No PRs found between branches');
-              process.exit();
-            }
-            const labels = JSON.parse(process.env.PULL_REQUESTS).flatMap(pr => pr.labels.map(label => label.name));
-            core.info(`Labels: ${labels.join(', ')}`);
-            let incrementType = 'patch';
-            if (labels.includes(process.env.MAJOR_LABEL)) {
-              console.log("Major changes found! Should increase major version.");
-              incrementType = 'major';
-            } else if (labels.includes(process.env.MINOR_LABEL)) {
-              console.log("Minor changes found! Should increase minor version.");
-              incrementType = 'minor';
-            } else if (labels.includes(process.env.PATCH_LABEL)) {
-              console.log("Patch changes found! Should increase patch version.");
-            } else {
-              console.log("No PRs labeled patch, minor or major found! Defaulting to 'patch'.");
-            }
-            core.setOutput('increment_type', incrementType);
+        run: |
+          if [ -z "$PULL_REQUESTS" ]; then
+            echo "Error: No PRs found between branches" && exit 1
+          fi
+          labels=$(echo "$PULL_REQUESTS" | jq -r '.[].labels[].name')
+          echo Labels: $labels
+          increment_type="patch"
+          case "$labels" in
+            *"${{ env.MAJOR_LABEL }}"*) increment_type="major"; echo "Major changes found! Should increase major version." ;;
+            *"${{ env.MINOR_LABEL }}"*) increment_type="minor"; echo "Minor changes found! Should increase minor version." ;;
+            *"${{ env.PATCH_LABEL }}"*) echo "Patch changes found! Should increase patch version." ;;
+            *) echo "No PRs labeled patch, minor or major found! Defaulting to 'patch'." ;;
+          esac
+          echo "increment_type=$increment_type" >> $GITHUB_OUTPUT
 
       - name: Calculate next version
         id: get-next-version
